// Полное бар-меню — перенос бумажных карточек в текст (SEO), 2026-07-05.
// Контент RU-only, как весь контент проекта (решение владельца).
//
// Структура: группы (якорная навигация) → категории (карточки в стиле бумажного
// меню) → позиции { name, origin?, volume?, price }. volume пуст → берётся
// unit категории; origin — страна/тип или состав коктейля (курсивом на карточке).
// quote — афоризм в конце карточки + рукописная подпись (Jar Binks).

// Тексты «немного истории» для правой панели на странице «Напитки».
// Ключ — точное название категории. Пока черновики-заглушки: владелец сказал,
// что подберёт свои тексты — менять только здесь, ничего больше трогать не надо.
export const CATEGORY_STORIES = {
  'Авторские коктейли': 'Авторский коктейль почти всегда «твист» — бармен берёт классику вроде Clover Club образца 1900-х и пересобирает её под характер бара: другой крепкий, свой сироп, неожиданная специя. Каждый рецепт этой карты родился за нашей стойкой.',
  'Домашние настойки': 'Настойки мы ставим сами: ягоды, чай и специи неделями отдают вкус алкоголю в бутылях за стойкой. Поэтому вкусы меняются с сезоном — спрашивайте, что настоялось сегодня.',
  'Ликёры и настойки': 'Ликёры — потомки аптечных эликсиров: когда-то травы на спирту продавали в аптеках как лекарство от всего. Лечебный эффект наука не подтвердила, а удовольствие — осталось.',
  'Биттеры и аперитивы': 'Горькие травяные настойки Италии и Франции открывают вечер: аперитив будит аппетит, биттер расставляет акценты в коктейлях. Пить можно и просто со льдом и содовой.',
  'Белые вина': 'Белое вино любит холод и молодость: почти всё в этой карте — свежие урожаи, которые пьются легко и первыми. Начинать вечер лучше именно с них.',
  'Красные вина': 'Красные подбираем лесенкой — от лёгкого пино нуара до плотного шираза: под настроение, музыку и время вечера. Чем позже час, тем плотнее бокал.',
  'Розовые и янтарные вина': 'Розе — не «недокрасное», а отдельный жанр. Янтарные (оранжевые) вина делают наоборот: белый виноград выдерживают на кожице, как красное — отсюда цвет и характер.',
  'Игристые вина': 'Пузырьки — заслуга второй ферментации в бутылке или танке. От строгого брюта до сладкого асти — свой уровень сладости можно искать всю жизнь.',
  'Безалкогольные вина': 'Тот же виноград и та же работа винодела — алкоголь бережно убирают уже из готового вина, оставляя вкус. Для тех, кто сегодня за рулём или просто так решил.',
  'Портвейн и херес': 'Креплёные вина пережили эпоху парусников: спирт добавляли, чтобы вино доплывало до колоний не испортившись. Доплыло — и осталось в мировой культуре навсегда.',
  'Креплёные вина и вермуты': 'Вермут — вино, настоянное на полыни и травах: основа половины классических коктейлей и отличный аперитив сам по себе. Полынь по-немецки — «вермут», отсюда и имя.',
  'Водка': 'Самый честный дистиллят: спрятаться не за что, только чистота сырья и воды. Подаём ледяной — и лучше с закусками с соседней страницы.',
  'Джин': 'Джин — это можжевельник плюс фантазия дистиллера: от голландского женевера XVI века до японского юдзу. Ботаники в составе могут быть любые — отсюда такой разброс вкусов.',
  'Ром и кашаса': 'Ром — биография Карибов в бутылке: сахарный тростник, жаркие склады и бочки из-под бурбона. Кашаса — бразильский кузен из свежего тростникового сока.',
  'Текила и мескаль': 'Оба рождаются из агавы: текила — строгая классика штата Халиско, мескаль — её дымный дикий родственник, который готовят в земляных печах.',
  'Шотландский виски': 'Шотландия делит виски на регионы, как Франция вино на терруары: мягкие равнины, фруктовый Спейсайд и торфяной дымный Айла. Найдите свой берег.',
  'Американский виски': 'Бурбон обязан характером кукурузе и обожжённой новой бочке: отсюда сладость, ваниль и карамель. Rye — его перечный старший брат.',
  'Виски со всего мира': 'Виски давно не только Шотландия: Япония, Мексика, Австралия и даже Италия гонят свой — и регулярно обыгрывают классиков на слепых дегустациях.',
  'Коньяк': 'Коньяк — виноградный спирт из одноимённого французского региона, дважды перегнанный и выдержанный в лимузенском дубе. Всё остальное в мире — просто бренди.',
  'Дистилляты': 'Писко, граппа, кальвадос, арманьяк — у каждой страны свой способ перегнать сад и виноградник в рюмку. Короткая кругосветка, не вставая со стула.',
  'Закуски к напиткам': 'Закуски здесь служат напиткам, а не наоборот: солёное и пряное — к крепкому, сыр и хамон — к вину, а гуакамоле выручает всех.',
};

export const BAR_MENU = [
  {
    id: 'cocktails',
    title: 'Коктейли и настойки',
    categories: [
      {
        title: 'Авторские коктейли',
        items: [
          { name: 'Clover Club Special', origin: 'ботаникал джин, одуванчик, лопух, малина, ягодно-фруктовый аперитив, белок, лайм', price: '750 ₽' },
          { name: 'Pinacolada', origin: 'выдержанный ром, белый ром, ананас, кокос, сливки', price: '700 ₽' },
          { name: 'La Gloria', origin: 'ботаникал джин, розовый перец, кардамон, арбуз, лайм', price: '850 ₽' },
          { name: 'Mezcalito Negroni', origin: 'мескаль, красный вермут, травяной биттер', price: '750 ₽' },
          { name: 'Orpheus', origin: 'карибский ром, ананас, маракуйя, алоэ, лайм, корица', price: '1 500 ₽' },
          { name: 'Peach Sidecar', origin: 'коньяк, ликёр из апельсинов, персиковый аперитив, лимон', price: '700 ₽' },
          { name: 'Pisco-Berry Sour', origin: 'писко, ягодный аперитив, ликёр из артишоков, белок, лайм', price: '750 ₽' },
          { name: 'Lady Cat', origin: 'мескаль, ликёр из бузины и горечавки, лайм, содовая', price: '950 ₽' },
          { name: 'El Presidente', origin: 'ром, сухой вермут, ликёр из апельсинов, сухой херес, гранат', price: '750 ₽' },
          { name: 'Aviation', origin: 'джин, ликёр из фиалки и вишни Мараска, лимон', price: '800 ₽' },
          { name: 'Pedro Manhattan', origin: 'бурбон, сладкий херес, биттер из грецкого ореха', price: '900 ₽' },
          { name: 'Penicillin', origin: 'виски островной и выдержанный, имбирь, лимон, мёд', price: '850 ₽' },
          { name: 'Inspiration', origin: 'джин, киви, лемонграсс, лайм, белок', price: '700 ₽' },
          { name: 'Martinez', origin: 'женевер, ликёр из артишоков, сухой вермут, ликёр вишня Мараска', price: '750 ₽' },
          { name: 'Grasshoper', origin: 'ликёр какао, ликёр мяты, сливки', price: '650 ₽' },
          { name: 'El Vampiro', origin: 'текила, томаты, Табаско, Ворчестер, соль, перец, лайм', price: '750 ₽' },
          { name: 'Pornstar Passion', origin: 'текила, маракуйя, ликёр горечавки, ваниль, ананас, лайм', price: '800 ₽' },
        ],
        quote: { text: 'Ты слишком прекрасен для воды и скучных вечеров.', author: "Cat's Pajamas Club" },
      },
      {
        title: 'Домашние настойки',
        unit: '50 мл',
        items: [
          { name: 'Малиновая на джине', origin: 'с лаймом и лемонграссом', price: '330 ₽' },
          { name: 'Том-Ям', price: '330 ₽' },
          { name: 'Фисташковый пломбир', price: '330 ₽' },
          { name: 'Смородина-Маракуйя', price: '330 ₽' },
          { name: 'ДаХунПао с инжиром на роме', price: '330 ₽' },
        ],
      },
      {
        title: 'Ликёры и настойки',
        unit: '40 мл',
        items: [
          { name: 'Limoncello di Capri Molinari', price: '380 ₽' },
          { name: 'Marolo Milla', price: '610 ₽' },
          { name: 'Frangelico', price: '700 ₽' },
          { name: 'Abasolo Nixta', price: '750 ₽' },
          { name: 'Becherovka Original', price: '380 ₽' },
          { name: 'Jagermeister', price: '380 ₽' },
          { name: 'Adriatico Amaretto Bianco', price: '600 ₽' },
          { name: 'Drambuie', price: '550 ₽' },
          { name: 'Amaro Montenegro', price: '500 ₽' },
          { name: 'Amaro Ulich', price: '520 ₽' },
        ],
      },
      {
        title: 'Биттеры и аперитивы',
        unit: '40 мл',
        items: [
          { name: 'Campari', price: '400 ₽' },
          { name: 'Aperol', price: '350 ₽' },
          { name: 'Cynar', price: '350 ₽' },
          { name: 'Sarti Rosa', price: '350 ₽' },
          { name: 'Chemer Red', price: '300 ₽' },
          { name: 'Chemer Green', price: '300 ₽' },
          { name: 'Suze', price: '510 ₽' },
          { name: 'RinQuinQuin a la Peche', price: '400 ₽' },
          { name: 'Noix de la Saint Jean', price: '400 ₽' },
          { name: 'Absente 55', price: '520 ₽' },
        ],
      },
    ],
  },
  {
    id: 'wine',
    title: 'Вина',
    categories: [
      {
        title: 'Белые вина',
        unit: '125 мл',
        items: [
          { name: 'Виньо Верде Оуш Буффе Бранко', origin: 'Португалия · полусухое', price: '370 ₽' },
          { name: 'Рислинг-Гевюрцтраминер Винцер фон Баден', origin: 'Германия · полусладкое', price: '450 ₽' },
          { name: 'Виоанье Бюрнье', origin: 'Россия · сухое', price: '430 ₽' },
          { name: 'Шардоне Оук Каск Трапиче', origin: 'Аргентина · сухое', price: '450 ₽' },
          { name: 'Грюнер Вельтлинер Беркёних Вайнгут Хенингер', origin: 'Австрия · сухое', price: '450 ₽' },
          { name: 'Совиньон Блан Арко Бэй', origin: 'Новая Зеландия · сухое', price: '350 ₽' },
          { name: 'Ассамбляж Люблю Бюрнье', origin: 'Россия · сухое', price: '350 ₽' },
          { name: 'Рислинг Михель Шайд Айних Зензен', origin: 'Германия · сухое', price: '450 ₽' },
        ],
        quote: { text: 'Антибиотики лечат людей, но счастливыми их может сделать только вино.', author: 'Александр Флеминг' },
      },
      {
        title: 'Красные вина',
        unit: '125 мл',
        items: [
          { name: 'Ассамбляж Люблю Бюрнье', origin: 'Россия · сухое', price: '350 ₽' },
          { name: 'Каберне Совиньон Бюрнье', origin: 'Россия · сухое', price: '400 ₽' },
          { name: 'Мальбек Вью Манент Эстейт Коллекшн Резерва', origin: 'Чили · сухое', price: '450 ₽' },
          { name: 'Пино Нуар Бушар Эне и Фис Гран Конселье', origin: 'Франция · сухое', price: '450 ₽' },
          { name: 'Риоха Темпранильо Льяно Рамон Бильбао', origin: 'Испания · сухое', price: '550 ₽' },
          { name: 'Шираз Кембридж Кроссинг', origin: 'Австралия · сухое', volume: '125 мл / 750 мл', price: '450 ₽ / 2 500 ₽' },
          { name: 'Примитиво Майя Чело', origin: 'Италия · полусухое', price: '540 ₽' },
          { name: 'Кьянти Ризерва Тре Чипресси Пиччини', origin: 'Италия · сухое', price: '500 ₽' },
        ],
      },
      {
        title: 'Розовые и янтарные вина',
        unit: '125 мл',
        items: [
          { name: 'Ркацители Оранж Эссе Анплагд Сатера', origin: 'Крым · сухое', price: '450 ₽' },
          { name: 'Ассамбляж Люблю Бюрнье', origin: 'розовое сухое', price: '350 ₽' },
          { name: 'Виньо Верде Петула Каза де Фонте Пекена', origin: 'розовое полусухое', price: '350 ₽' },
          { name: 'Уайт Зинфандель Санта Моника', origin: 'США · полусладкое', price: '500 ₽' },
        ],
      },
      {
        title: 'Игристые вина',
        unit: '125 мл',
        items: [
          { name: 'Кава Нувиана Росадо', origin: 'Испания · розовое брют', price: '450 ₽' },
          { name: 'Просекко Белвила Экстра Драй', origin: 'Италия · сухое', price: '500 ₽' },
          { name: 'Спуманте Терре дель Додже Бьянко', origin: 'Италия · брют', price: '450 ₽' },
          { name: 'Балаклава Резерв Золотая Балка', origin: 'Крым · розовое брют', price: '350 ₽' },
          { name: "Асти Фиорино д'Оро", origin: 'Италия · сладкое', price: '550 ₽' },
          { name: "Креман д'Эльзас Бенвир", origin: 'Франция · брют', price: '700 ₽' },
          { name: 'Шампанское Луи Арман', origin: 'Франция · брют', volume: '750 мл', price: '9 500 ₽' },
        ],
      },
      {
        title: 'Безалкогольные вина',
        unit: '125 мл',
        items: [
          { name: 'Красное', origin: 'Испания', price: '300 ₽' },
          { name: 'Белое', origin: 'Испания', price: '300 ₽' },
          { name: 'Игристое', origin: 'Испания', price: '400 ₽' },
        ],
      },
      {
        title: 'Портвейн и херес',
        unit: '75 мл',
        items: [
          { name: 'Infantado Porto Ruby', origin: 'Португалия', price: '850 ₽' },
          { name: 'Quinta do Infantado Porto LBV', origin: 'Португалия', price: '1 500 ₽' },
          { name: 'KWV Classic Cape Red Muscadel', origin: 'ЮАР', price: '480 ₽' },
          { name: 'Duquesa Pedro Ximenez Jerez', origin: 'Испания', price: '1 200 ₽' },
          { name: 'Marismeno Fino Jerez', origin: 'Испания', price: '1 000 ₽' },
        ],
      },
      {
        title: 'Креплёные вина и вермуты',
        items: [
          { name: 'Cinzano Bianco', volume: '80 мл', price: '400 ₽' },
          { name: 'Cinzano 1757 Rosso', volume: '80 мл', price: '400 ₽' },
          { name: 'Cinzano Extra Dry', volume: '80 мл', price: '400 ₽' },
          { name: "Otto's Athens Vermouth", volume: '40 мл', price: '350 ₽' },
          { name: 'Carlo Alberto Red', volume: '80 мл', price: '600 ₽' },
          { name: 'Byrrh Grand Quinquina', volume: '40 мл', price: '500 ₽' },
          { name: 'Vermouth Dry de Provence', volume: '40 мл', price: '450 ₽' },
        ],
      },
    ],
  },
  {
    id: 'spirits',
    title: 'Крепкий алкоголь',
    categories: [
      {
        title: 'Водка',
        unit: '50 мл',
        items: [
          { name: 'Онегин', origin: 'Россия', price: '380 ₽' },
          { name: 'Царская Золотая', origin: 'Россия', price: '280 ₽' },
          { name: 'Schmidt Supreme / Grapefruit / Blackcurrant', origin: 'Беларусь', price: '350 ₽' },
          { name: 'Ortodox Vodka', origin: 'Россия', price: '300 ₽' },
          { name: 'Niki Pure', origin: 'Россия', price: '460 ₽' },
          { name: 'Mont Blanc', origin: 'Франция', price: '480 ₽' },
        ],
        quote: { text: 'Истина в вине, а в водке — горькая правда.', author: 'народная мудрость' },
      },
      {
        title: 'Джин',
        unit: '40 мл',
        items: [
          { name: "Bobby's Scheidam Gin", origin: 'Нидерланды', price: '700 ₽' },
          { name: 'Gintl Premium Gin', origin: 'Россия', price: '450 ₽' },
          { name: 'Four Pillars Olive Leaf', origin: 'Австралия', price: '800 ₽' },
          { name: 'Four Pillars Bloody Shiraz', origin: 'Австралия', price: '950 ₽' },
          { name: 'Cross Keys Botanical Gin', origin: 'Латвия', price: '580 ₽' },
          { name: 'Cross Keys Blackcurrant', origin: 'Латвия', price: '580 ₽' },
          { name: 'Bols Genever Barrel Aged', origin: 'Нидерланды', price: '500 ₽' },
          { name: "Porter's Tropical Old Tom Gin", origin: 'Шотландия', price: '770 ₽' },
          { name: 'Citadelle Gin', origin: 'Франция', price: '580 ₽' },
          { name: 'Etsu Double Yuzu', origin: 'Япония', price: '800 ₽' },
          { name: 'Berkshire Dundelock', origin: 'Великобритания', price: '450 ₽' },
        ],
      },
      {
        title: 'Ром и кашаса',
        unit: '40 мл',
        items: [
          { name: "Chairman's Reserve Spiced", origin: 'Сент-Люсия', price: '500 ₽' },
          { name: "The Demon's Share 6 Y.O.", origin: 'Панама', price: '610 ₽' },
          { name: 'Botran Cobre Spiced Ron', origin: 'Гватемала', price: '1 000 ₽' },
          { name: 'Velho Barrero Cachasa 3 Anos', origin: 'Бразилия', price: '470 ₽' },
          { name: 'Angostura 7 Y.O.', origin: 'Тринидад и Тобаго', price: '720 ₽' },
          { name: 'Beach House White Spiced', origin: 'Франция', price: '600 ₽' },
          { name: 'Cihuatan Xaman XO', origin: 'Эль-Сальвадор', price: '1 600 ₽' },
          { name: 'Saint James VSOP Rhum Agricole AOC', origin: 'Мартиника', price: '570 ₽' },
          { name: 'Diplomatico Reserva Exclusiva', origin: 'Венесуэла', price: '700 ₽' },
          { name: 'Viejo de Caldas Gran Reserva Especiale 15 Y.O.', origin: 'Колумбия', price: '590 ₽' },
          { name: 'Authentico Nativo Overproof 8 Y.O.', origin: 'Панама', price: '950 ₽' },
          { name: 'Bumbu Original Rum 15 Y.O.', origin: 'Барбадос', price: '750 ₽' },
          { name: 'Legendario Elixir de Cuba 7 Y.O.', origin: 'Куба', price: '630 ₽' },
          { name: 'Matusalem Insolito Wine Cask Finish', origin: 'Доминикана', price: '750 ₽' },
          { name: 'Tahitian Queen Pineapple Rum', origin: 'Таити', price: '650 ₽' },
        ],
      },
      {
        title: 'Текила и мескаль',
        unit: '40 мл',
        items: [
          { name: 'Espolon Blanco Tequila', price: '550 ₽' },
          { name: 'Espolon Anejo Tequila', price: '720 ₽' },
          { name: 'Grand La Escondida Mezcal', price: '700 ₽' },
          { name: 'Ojo de Tigre Espadin-Tabola Mezcal', price: '680 ₽' },
          { name: 'Grand La Escondida Sotol', price: '600 ₽' },
          { name: 'Pelaton De La Muerte Mezcal', price: '690 ₽' },
          { name: 'Jose Cuervo 1800 Cristalino Anejo', price: '1 200 ₽' },
          { name: 'Estancia Raicilla', price: '770 ₽' },
        ],
      },
      {
        title: 'Шотландский виски',
        unit: '40 мл',
        items: [
          { name: 'The Gild Blended Whisky', price: '600 ₽' },
          { name: 'Catty Sark 12 Y.O.', price: '650 ₽' },
          { name: 'Loch Lomond Single Grain Peated', price: '630 ₽' },
          { name: 'Bankholl Single Rye Whisky', price: '500 ₽' },
          { name: 'Balvenie Doublewood 12 Y.O.', price: '1 250 ₽' },
          { name: 'Glen Scotia 10 Y.O.', price: '1 050 ₽' },
          { name: 'The Dalmore 12 Y.O.', price: '1 350 ₽' },
          { name: 'Laphroaig 10 Y.O.', price: '900 ₽' },
          { name: 'Glenfarclas 10 Y.O.', price: '1 050 ₽' },
        ],
      },
      {
        title: 'Американский виски',
        unit: '40 мл',
        items: [
          { name: "Jack Daniel's Single Barrel", price: '1 150 ₽' },
          { name: "Maker's Mark Bourbon", price: '720 ₽' },
          { name: 'Whiskey Stateless', price: '500 ₽' },
          { name: 'Four Roses Small Batch Bourbon', price: '900 ₽' },
          { name: 'Woodford Reserve Bourbon', price: '700 ₽' },
        ],
      },
      {
        title: 'Виски со всего мира',
        unit: '40 мл',
        items: [
          { name: 'Abasolo Alma de Terra Mexican Whiskey', origin: 'Мексика', price: '750 ₽' },
          { name: 'The Tottori Blended Whisky', origin: 'Япония', price: '750 ₽' },
          { name: 'Heriose Le Petit Tourbe', origin: 'Франция', price: '1 100 ₽' },
          { name: 'The Gospel Solera Rye', origin: 'Австралия', price: '700 ₽' },
          { name: 'Kapriol Whisky', origin: 'Италия', price: '650 ₽' },
        ],
        quote: { text: 'Плохого виски не бывает. Просто некоторые сорта виски лучше других.', author: 'Джордж Бернард Шоу' },
      },
      {
        title: 'Коньяк',
        unit: '40 мл',
        items: [
          { name: 'Francois de Martignac VS', price: '700 ₽' },
          { name: 'Francois de Martignac VSOP', price: '900 ₽' },
          { name: 'Roullet VS', price: '600 ₽' },
          { name: 'Courvoisier VSOP', price: '950 ₽' },
          { name: 'Chateau de Montifaud 10 Y.O.', origin: 'Grande Champagne AOC', price: '1 100 ₽' },
        ],
      },
      {
        title: 'Дистилляты',
        unit: '40 мл',
        items: [
          { name: 'Vinias De Oro Quebranta Pisco', origin: 'Перу', price: '800 ₽' },
          { name: 'Sibona Riserva Grappa Sauternes Wood Finish', origin: 'Италия', price: '380 ₽' },
          { name: 'Calvados Coquerel VSOP', origin: 'Франция', price: '420 ₽' },
          { name: 'Brandy Torres 20 Y.O.', origin: 'Испания', price: '460 ₽' },
          { name: 'Chemer Barrel', origin: 'Бельгия', price: '440 ₽' },
          { name: 'Linie Aquavit Authentic', origin: 'Норвегия', price: '520 ₽' },
          { name: 'Janneau Napoleon Armagnac', origin: 'Франция', price: '850 ₽' },
        ],
      },
    ],
  },
  {
    id: 'snacks',
    title: 'Закуски',
    categories: [
      {
        title: 'Закуски к напиткам',
        items: [
          { name: 'Гуакамоле', volume: '160 г', price: '440 ₽' },
          { name: 'Фаршированные перчики', volume: '120 г', price: '520 ₽' },
          { name: 'Жареные артишоки', volume: '100 г', price: '460 ₽' },
          { name: 'Мухаммара с тостами', volume: '180 г', price: '420 ₽' },
          { name: 'Пикантин с томатным вареньем', volume: '70 г', price: '380 ₽' },
          { name: 'Сладкие перцы тонато', volume: '120 г', price: '460 ₽' },
          { name: 'Хамон', volume: '70 г', price: '800 ₽' },
          { name: 'Салями фуэт', volume: '70 г', price: '380 ₽' },
          { name: 'Белпер Кнолле', volume: '100 г', price: '420 ₽' },
          { name: 'Оливки', volume: '120 г', price: '460 ₽' },
          { name: 'Маринованные перепелиные яйца', volume: '120 г', price: '440 ₽' },
          { name: 'Риет ягнёнка', volume: '160 г', price: '480 ₽' },
          { name: 'Парфе с маринованным инжиром', volume: '160 г', price: '480 ₽' },
        ],
      },
    ],
  },
];
