// Backdrop photo per book page — shared by App.jsx (global page-bg layer)
// and Nav.jsx (small per-link thumbnail). Placeholders from the existing
// asset set; the client plans to source small custom photos per section
// later — just swap the paths here when that happens.
export const pageImages = {
  hero:     '/uploads/team/cocktails.jpg',
  about:    '/uploads/team/bar-interior.jpg',
  menu:     '/uploads/team/clover-club.jpg',
  events:   '/uploads/team/live-music.jpg',
  gallery:  '/uploads/team/bar-hall.jpg',
  team:     '/uploads/team/team-group.jpg',
  booking:  '/uploads/team/bar-evening.jpg',
  contacts: '/uploads/team/bar-atmosphere.jpg',
};

export const translations = {
  ru: {
    langBtn: 'EN',
    navAbout: 'Легенда', navMenu: 'Напитки', navEvents: 'Афиша',
    navGallery: 'Полка', navTeam: 'Бармены', navContacts: 'Как найти',
    navLoginTg: 'Войти через Telegram', navProfile: 'Профиль',
    navAdmin: 'Админ-панель',
    heroEdition: 'Барная карта',
    heroCta: 'Забронировать стол',
    heroTagline: 'Место, где джаз не заканчивается',
    heroSub: 'Самара · Коктейли · Живая музыка',
    heroNext: 'Открыть карту',

    aboutLabel: 'Глава I · Легенда бара',
    aboutQuote: '«Здесь джаз звучит даже в тишине»',
    // TODO: финальный текст и реальные факты (год открытия, точные часы) — уточнить у клиента
    aboutText: [
      'The Cat\'s Pajamas Club — джаз-бар в самом сердце Самары, на улице Куйбышева. Мы собрали под одной крышей дух нью-йоркских speakeasy эпохи Сухого закона: тёмный дуб, латунь, бархат и приглушённый свет, в котором каждый вечер звучит живая музыка.',
      'Наша карта — больше полусотни авторских и классических коктейлей: от выверенной классики до сезонных миксов, которые бармены придумывают сами. Здесь напиток — это точка зрения, а не просто рецепт, а джаз на сцене превращает обычный вечер в историю.',
      'Мы открыты каждый день до глубокой ночи: с воскресенья по четверг — до 02:00, в пятницу и субботу — до 04:00. Приходите послушать живой джаз, попробовать коктейль с характером и остаться до последнего аккорда.',
    ],

    menuLabel: 'Глава II · Карта напитков', menuTitle: 'Коктейльная карта',
    menuClassics: 'Классика', menuSignature: 'Авторский',
    menuCta: 'Забронировать столик',
    menuLoading: 'Загружаем меню…',
    menuEmpty: 'Меню скоро пополнится.',
    menuStoryLabel: 'О разделе',
    menuPrintLink: 'Открыть карту отдельной страницей',

    eventsLabel: 'Глава III · Вечерняя афиша', eventsTitle: 'Джазовая программа',
    eventsLoading: 'Загружаем события…',
    eventsEmpty: 'Ближайших событий пока нет — загляните позже.',

    galleryLabel: 'Глава IV · Каждый гость — своя бутылка', galleryTitle: 'Полка воспоминаний',
    galleryIntro: 'Каждый отзыв гостя становится бутылкой на нашей полке. Загляните — вдруг узнаете чей-то вечер.',

    teamLabel: 'Глава V · За барной стойкой', teamTitle: 'Мастера за стойкой',
    teamSub: 'Каждый из наших барменов — это история, прожитая в коктейлях.',
    teamLoading: 'Загружаем команду…',
    teamEmpty: 'Скоро здесь появится команда.',
    teamJoinText: 'Поделись своим опытом — нам нужны лучшие бармены',
    teamJoinBtn: 'Оставить заявку',
    teamJoinAsk: 'Хочешь попасть в команду профессионалов?',
    teamJoinShare: 'Поделись своим опытом',
    teamJoinName: 'Ваше имя',
    teamJoinPhone: 'Телефон',
    teamJoinExp: 'Коротко о вашем опыте',
    teamJoinSend: 'Отправить',
    teamJoinSuccess: 'Спасибо! Мы свяжемся с вами в ближайшее время.',

    reviewsLoading: 'Расставляем бутылки…',
    reviewsEmpty: 'Полка пока пуста — станьте первым, кто оставит воспоминание.',
    shelfCtaLoggedOut: 'Войдите, чтобы оставить отзыв',
    shelfCtaLoggedIn: '📝 Оставить отзыв',
    shelfModalTitle: 'Пополните полку',
    shelfModalText: 'Отзывы хранятся в нашем Telegram-обсуждении. Оставьте сообщение там — и оно появится здесь новой бутылкой.',
    shelfModalBtn: 'Оставить воспоминание',
    shelfModalClose: 'Закрыть',
    shelfReadClose: 'Закрыть',

    bookingLabel: 'Последняя страница', bookingTitle: 'Займите свой столик',
    phoneLabel: 'Телефон',

    // ─── Бронирование v2 (план зала + заявка) ───
    bkDateLabel: 'Дата', bkTimeLabel: 'Приход к',
    bkToday: 'Сегодня', bkTomorrow: 'Завтра',
    bkClosedToday: 'На этот вечер заявки уже не принимаются — выберите другой день',
    bkLoading: 'Загружаем план зала…',
    bkStatusVacant: 'Свободен', bkStatusReservedAt: 'Бронь к', bkStatusOccupied: 'Занят',
    bkBarNote: 'Стойка не бронируется — просто приходите',
    bkLegendVacant: 'Свободен', bkLegendReserved: 'Бронь', bkLegendOccupied: 'Занят',
    bkTableWord: 'Стол', bkSofa: 'Диван',
    bkZoneMain: 'Основной зал', bkZoneWindow: 'У окна', bkZoneSofas: 'Диваны',
    bkSeatsLabel: 'мест',
    bkPanelHint: 'Выберите свободный стол на плане',
    bkPanelPhone: 'Нет Telegram? Забронируйте по телефону:',
    bkReservedText: 'Стол уже ждёт гостей в этот вечер — выберите другой.',
    bkOccupiedText: 'Стол сейчас занят. Выберите другой — или приходите к стойке, она не бронируется.',
    bkAuthText: 'План зала открыт всем — для брони нужен вход через Telegram.',
    bkAuthBtn: 'Войти через Telegram',
    bkFormName: 'Ваше имя *', bkFormPhone: 'Телефон',
    bkFormGuests: 'Гостей', bkFormNote: 'Пожелания',
    bkFormNotePh: 'День рождения, столик ближе к сцене…',
    bkFormSubmit: 'Отправить заявку', bkFormSubmitting: 'Отправляем…',
    bkConfirmNote: 'Бронь подтверждает бармен — уведомление придёт в Telegram.',
    bkSuccessTitle: 'Заявка отправлена!',
    bkSuccessText: 'Бронь подтверждает бармен — обычно это занимает несколько минут. Уведомление придёт в Telegram от @cats_pajama_bot.',
    bkSuccessWhere: 'Статус заявки виден в вашем профиле и в «Мои брони» в боте.',
    bkSuccessOk: 'Хорошо',
    bkDepositLabel: 'Депозит',
    bkDepositNote: 'Оплата после подтверждения бармена — в «Мои брони». Депозит засчитывается в счёт заказа.',
    bkSuccessDeposit: 'После подтверждения оплатите депозит в «Мои брони» — он засчитается в счёт заказа.',
    bkTgFallbackText: 'Не нашли нужный стол? Большая компания?',
    bkTgFallbackText2: 'Оставьте заявку в Telegram — что-нибудь придумаем 🎷',
    bkTgFallbackBtn: 'Написать в Telegram',

    contactsLabel: 'Глава VI · Как нас найти', contactsTitle: 'Найти бар',
    addressLabel: 'Адрес', address: 'г. Самара, ул. Куйбышева, 100',
    hoursLabel: 'Часы работы',
    daysWeek: 'Пн – Чт, Вс', daysWend: 'Пт – Сб',
    mapLabel: 'Открыть на Яндекс.Картах',
    footerBookingRules: 'Правила бронирования',
    footerPrivacy: 'Политика конфиденциальности',
    footerCopy: '© 2025 The Cat\'s Pajamas Club · Самара',
  },
  en: {
    langBtn: 'RU',
    navAbout: 'Legend', navMenu: 'Drinks', navEvents: 'Bill',
    navGallery: 'Shelf', navTeam: 'Bartenders', navContacts: 'Find Us',
    navLoginTg: 'Log in with Telegram', navProfile: 'Profile',
    navAdmin: 'Admin Panel',
    heroEdition: 'The Bar Menu',
    heroCta: 'Reserve a Table',
    heroTagline: 'Where the Jazz Never Stops',
    heroSub: 'Samara · Cocktails · Live Music',
    heroNext: 'Open the Menu',

    aboutLabel: 'Chapter I · The Legend',
    aboutQuote: '"Where jazz plays even in the silence"',
    // TODO: final copy and real facts (opening year, exact hours) — confirm with client
    aboutText: [
      'The Cat\'s Pajamas Club is a jazz bar in the heart of Samara, on Kuybysheva Street. Under one roof we\'ve gathered the spirit of New York speakeasies from the Prohibition era: dark oak, brass, velvet, and dim light filled with live music every night.',
      'Our menu holds over fifty signature and classic cocktails — from precise classics to seasonal mixes our bartenders invent themselves. Here a drink is a point of view, not just a recipe, and the jazz on stage turns an ordinary evening into a story.',
      'We\'re open every night until late: Sunday through Thursday until 2 AM, Friday and Saturday until 4 AM. Come for live jazz, a cocktail with character, and stay until the last chord.',
    ],

    // NB: cocktail content itself is RU-only (owner's decision) — these are
    // just the surrounding UI labels for the EN toggle.
    menuLabel: 'Chapter II · The Drinks List', menuTitle: 'The Cocktail List',
    menuClassics: 'Classic', menuSignature: 'Signature',
    menuCta: 'Reserve a Table',
    menuLoading: 'Loading the menu…',
    menuEmpty: 'The menu is coming soon.',
    menuStoryLabel: 'About this section',
    menuPrintLink: 'Open the menu as a separate page',

    eventsLabel: 'Chapter III · Evening Bill', eventsTitle: 'The Jazz Program',
    eventsLoading: 'Loading events…',
    eventsEmpty: 'No upcoming events yet — check back soon.',

    galleryLabel: 'Chapter IV · Every Guest, Their Own Bottle', galleryTitle: 'Shelf of Memories',
    galleryIntro: 'Every guest review becomes a bottle on our shelf. Take a look — you might recognize someone\'s evening.',

    teamLabel: 'Chapter V · Behind the Bar', teamTitle: 'Masters Behind the Bar',
    teamSub: 'Each of our bartenders is a story lived through cocktails.',
    teamLoading: 'Loading the team…',
    teamEmpty: 'The team page is coming soon.',
    teamJoinText: 'Share your experience — we\'re looking for the best bartenders',
    teamJoinBtn: 'Apply Now',
    teamJoinAsk: 'Want to join a team of professionals?',
    teamJoinShare: 'Share your experience',
    teamJoinName: 'Your name',
    teamJoinPhone: 'Phone',
    teamJoinExp: 'A bit about your experience',
    teamJoinSend: 'Send',
    teamJoinSuccess: 'Thank you! We\'ll be in touch soon.',

    reviewsLoading: 'Arranging the bottles…',
    reviewsEmpty: 'The shelf is empty — be the first to leave a memory.',
    shelfCtaLoggedOut: 'Sign in to leave a review',
    shelfCtaLoggedIn: '📝 Leave a review',
    shelfModalTitle: 'Fill the shelf',
    shelfModalText: 'Reviews live in our Telegram discussion. Post a message there and it will appear here as a new bottle.',
    shelfModalBtn: 'Leave a memory',
    shelfModalClose: 'Close',
    shelfReadClose: 'Close',

    bookingLabel: 'The Final Page', bookingTitle: 'Claim Your Table',
    phoneLabel: 'Phone',

    // ─── Booking v2 (floor plan + request) ───
    bkDateLabel: 'Date', bkTimeLabel: 'Arriving at',
    bkToday: 'Today', bkTomorrow: 'Tomorrow',
    bkClosedToday: 'Requests for tonight are closed — pick another day',
    bkLoading: 'Loading the floor plan…',
    bkStatusVacant: 'Free', bkStatusReservedAt: 'Booked for', bkStatusOccupied: 'Taken',
    bkBarNote: 'The bar counter is walk-in only',
    bkLegendVacant: 'Free', bkLegendReserved: 'Booked', bkLegendOccupied: 'Taken',
    bkTableWord: 'Table', bkSofa: 'Sofa',
    bkZoneMain: 'Main hall', bkZoneWindow: 'By the window', bkZoneSofas: 'Sofas',
    bkSeatsLabel: 'seats',
    bkPanelHint: 'Pick a free table on the plan',
    bkPanelPhone: 'No Telegram? Book by phone:',
    bkReservedText: 'This table is already spoken for tonight — pick another one.',
    bkOccupiedText: 'This table is taken right now. Pick another — or come sit at the bar, it\'s walk-in only.',
    bkAuthText: 'The floor plan is open to everyone — booking requires a Telegram login.',
    bkAuthBtn: 'Log in with Telegram',
    bkFormName: 'Your name *', bkFormPhone: 'Phone',
    bkFormGuests: 'Guests', bkFormNote: 'Requests',
    bkFormNotePh: 'A birthday, a table near the stage…',
    bkFormSubmit: 'Send request', bkFormSubmitting: 'Sending…',
    bkConfirmNote: 'A bartender confirms every booking — you\'ll get a Telegram notification.',
    bkSuccessTitle: 'Request sent!',
    bkSuccessText: 'A bartender confirms every booking — it usually takes a few minutes. The notification will arrive in Telegram from @cats_pajama_bot.',
    bkSuccessWhere: 'Track the status in your profile or in the bot\'s "My bookings".',
    bkSuccessOk: 'Got it',
    bkDepositLabel: 'Deposit',
    bkDepositNote: 'Payable in "My bookings" once a bartender confirms. The deposit counts toward your bill.',
    bkSuccessDeposit: 'Once confirmed, pay the deposit in "My bookings" — it counts toward your bill.',
    bkTgFallbackText: 'Can\'t find the right table? Big party?',
    bkTgFallbackText2: 'Drop us a line on Telegram — we\'ll figure something out 🎷',
    bkTgFallbackBtn: 'Message us on Telegram',

    contactsLabel: 'Chapter VI · Find Us', contactsTitle: 'Find The Bar',
    addressLabel: 'Address', address: 'Samara, Kuybysheva St, 100',
    hoursLabel: 'Hours',
    daysWeek: 'Mon – Thu, Sun', daysWend: 'Fri – Sat',
    mapLabel: 'Open on Yandex Maps',
    footerBookingRules: 'Booking Rules',
    footerPrivacy: 'Privacy Policy',
    footerCopy: '© 2025 The Cat\'s Pajamas Club · Samara',
  },
};


