// Backdrop photo per book page — shared by App.jsx (global page-bg layer)
// and Nav.jsx (small per-link thumbnail). Placeholders from the existing
// asset set; the client plans to source small custom photos per section
// later — just swap the paths here when that happens.
export const pageImages = {
  hero:     '/uploads/team/cocktails.jpg',
  about:    '/uploads/team/bar-interior.jpg',
  menu:     '/uploads/team/clover-club.jpg',
  events:   '/uploads/team/live-music.jpg',
  gallery:  '/uploads/team/bar-hall.jpg',
  team:     '/uploads/team/team-group.jpg',
  booking:  '/uploads/team/bar-evening.jpg',
  contacts: '/uploads/team/bar-atmosphere.jpg',
};

export const translations = {
  ru: {
    langBtn: 'EN',
    navAbout: 'Легенда', navMenu: 'Напитки', navEvents: 'Афиша',
    navGallery: 'Полка', navTeam: 'Бармены', navContacts: 'Как найти',
    navLoginTg: 'Войти через Telegram', navProfile: 'Профиль',
    navAdmin: 'Админ-панель',
    heroEdition: 'Барная карта',
    heroCta: 'Забронировать стол',
    heroTagline: 'Место, где джаз не заканчивается',
    heroSub: 'Самара · Коктейли · Живая музыка',
    heroNext: 'Открыть карту',

    aboutLabel: 'Глава I · Легенда бара',
    aboutQuote: '«Здесь джаз звучит даже в тишине»',
    // Легенда: тон и факты сведены из статьи в прессе и отзывов гостей.
    // Намеренно БЕЗ часов работы (они в «Как найти»), без числа позиций и без
    // названий коктейлей/настоек — меню постоянно меняется, хвастаемся качеством
    // и мастерством, а не количеством. Концепция: гость рассказывает о своём
    // вкусе — бармен уже знает, что делать. «Пижама Кота» — русское написание,
    // по нему бар ищут в поиске (SEO). Секция листается (см. .about в index.css).
    aboutText: [
      'The Cat\'s Pajamas Club, для своих просто «Пижама Кота», — камерный авторский коктейль-бар в центре Самары, на улице Куйбышева. Гости не раз называли его лучшим баром города, и мы стараемся держать эту планку каждый вечер. Внутри — атмосфера нью-йоркского бара 80-х: тёмное дерево, латунь и бархат, приглушённый свет, живой джаз и панорамное окно с видом на вечерний город.',
      'Название говорит само за себя: мы сознательно отказались от снобизма и лишнего пафоса. Каждый коктейль здесь мы собираем как маленький спектакль — со своим характером, неожиданным поворотом и вкусом, который хочется вспоминать. И чтобы получить свой, не нужно разбираться в барной карте: просто расскажите, что вам по душе, — а бармен уже знает, что делать.',
      'Бармен у нас — главный герой вечера. Он расспросит о ваших привычках и настроении и соберёт напиток лично под вас, иногда с личным, только вашим названием. Гости называют это то волшебством, то искусством, а мы просто точно попадаем во вкус. Мы гордимся не длиной карты, а мастерством за стойкой — каждый рецепт рождается здесь, у гостя на глазах.',
      'Отдельная гордость — авторские настойки: их неспешно настаивают прямо за стойкой, и каждого гостя мы встречаем угощением из этой коллекции. За качеством следим всерьёз: крепкий алкоголь уровня лучших мировых баров и продуманная винная карта — от редких находок до достойных отечественных вин. А безалкогольные коктейли собираем так же тщательно, как остальные, — чтобы вечер удался и у тех, кто сегодня за рулём.',
      'Но приходят сюда не только за напитками. «Пижама Кота» — это когда заходишь не в бар, а будто в гости к друзьям: тёплая обстановка, персональное внимание и разговоры по душам. В интерьере полно деталей, которые хочется рассматривать, а вода на столе не заканчивается весь вечер. По будням у нас тихо и камерно, по выходным звучит живая музыка.',
      'Это место для тех, кто ценит вкус и чувствует разницу между хорошим и посредственным, — для неспешного вечера с любимым человеком или близкими по духу. Сюда приходят не торопясь: медленно потягивать бокал, говорить обо всём на свете и уходить лишь тогда, когда по-настоящему насытишься — и напитками, и самим вечером. Загляните — и просто расскажите, что вам по вкусу.',
    ],

    menuLabel: 'Глава II · Карта напитков', menuTitle: 'Коктейльная карта',
    menuClassics: 'Классика', menuSignature: 'Авторский',
    menuCta: 'Забронировать столик',
    menuLoading: 'Загружаем меню…',
    menuEmpty: 'Меню скоро пополнится.',
    menuStoryLabel: 'О разделе',
    menuPrintLink: 'Открыть карту отдельной страницей',

    eventsLabel: 'Глава III · Вечерняя афиша', eventsTitle: 'Джазовая программа',
    eventsLoading: 'Загружаем события…',
    eventsEmpty: 'Ближайших событий пока нет — загляните позже.',

    galleryLabel: 'Глава IV · Каждый гость — своя бутылка', galleryTitle: 'Полка воспоминаний',
    galleryIntro: 'Каждый отзыв гостя становится бутылкой на нашей полке. Загляните — вдруг узнаете чей-то вечер.',

    teamLabel: 'Глава V · За барной стойкой', teamTitle: 'Мастера за стойкой',
    teamSub: 'Каждый из наших барменов — это история, прожитая в коктейлях.',
    teamLoading: 'Загружаем команду…',
    teamEmpty: 'Скоро здесь появится команда.',
    teamJoinText: 'Поделись своим опытом — нам нужны лучшие бармены',
    teamJoinBtn: 'Оставить заявку',
    teamJoinAsk: 'Хочешь попасть в команду профессионалов?',
    teamJoinShare: 'Поделись своим опытом',
    teamJoinName: 'Ваше имя',
    teamJoinPhone: 'Телефон',
    teamJoinExp: 'Коротко о вашем опыте',
    teamJoinSend: 'Отправить',
    teamJoinSuccess: 'Спасибо! Мы свяжемся с вами в ближайшее время.',

    reviewsLoading: 'Расставляем бутылки…',
    reviewsEmpty: 'Полка пока пуста — станьте первым, кто оставит воспоминание.',
    shelfCtaLoggedOut: 'Войдите, чтобы оставить отзыв',
    shelfCtaLoggedIn: '📝 Оставить отзыв',
    shelfModalTitle: 'Пополните полку',
    shelfModalText: 'Отзывы хранятся в нашем Telegram-обсуждении. Оставьте сообщение там — и оно появится здесь новой бутылкой.',
    shelfModalBtn: 'Оставить воспоминание',
    shelfModalClose: 'Закрыть',
    shelfReadClose: 'Закрыть',

    bookingLabel: 'Последняя страница', bookingTitle: 'Займите свой столик',
    phoneLabel: 'Телефон',

    // ─── Бронирование v2 (план зала + заявка) ───
    bkDateLabel: 'Дата', bkTimeLabel: 'Приход к',
    bkToday: 'Сегодня', bkTomorrow: 'Завтра',
    bkClosedToday: 'На этот вечер заявки уже не принимаются — выберите другой день',
    bkLoading: 'Загружаем план зала…',
    bkStatusVacant: 'Свободен', bkStatusReservedAt: 'Бронь к', bkStatusOccupied: 'Занят',
    bkBarNote: 'Стойка не бронируется — просто приходите',
    bkLegendVacant: 'Свободен', bkLegendReserved: 'Бронь', bkLegendOccupied: 'Занят',
    bkTableWord: 'Стол', bkSofa: 'Диван',
    bkZoneMain: 'Основной зал', bkZoneWindow: 'У окна', bkZoneSofas: 'Диваны',
    bkSeatsLabel: 'мест',
    bkPanelHint: 'Выберите свободный стол на плане',
    bkPanelPhone: 'Нет Telegram? Забронируйте по телефону:',
    bkReservedText: 'Стол уже ждёт гостей в этот вечер — выберите другой.',
    bkOccupiedText: 'Стол сейчас занят. Выберите другой — или приходите к стойке, она не бронируется.',
    bkAuthText: 'План зала открыт всем — для брони нужен вход через Telegram.',
    bkAuthBtn: 'Войти через Telegram',
    bkFormName: 'Ваше имя *', bkFormPhone: 'Телефон',
    bkFormGuests: 'Гостей', bkFormNote: 'Пожелания',
    bkFormNotePh: 'День рождения, столик ближе к сцене…',
    bkFormSubmit: 'Отправить заявку', bkFormSubmitting: 'Отправляем…',
    bkConfirmNote: 'Бронь подтверждает бармен — уведомление придёт в Telegram.',
    bkSuccessTitle: 'Заявка отправлена!',
    bkSuccessText: 'Бронь подтверждает бармен — обычно это занимает несколько минут. Уведомление придёт в Telegram от @cats_pajama_bot.',
    bkSuccessWhere: 'Статус заявки виден в вашем профиле и в «Мои брони» в боте.',
    bkSuccessOk: 'Хорошо',
    bkDepositLabel: 'Депозит',
    bkDepositNote: 'Оплата после подтверждения бармена — в «Мои брони». Депозит засчитывается в счёт заказа.',
    bkSuccessDeposit: 'После подтверждения оплатите депозит в «Мои брони» — он засчитается в счёт заказа.',
    bkTgFallbackText: 'Не нашли нужный стол? Большая компания?',
    bkTgFallbackText2: 'Оставьте заявку в Telegram — что-нибудь придумаем 🎷',
    bkTgFallbackBtn: 'Написать в Telegram',

    contactsLabel: 'Глава VI · Как нас найти', contactsTitle: 'Найти бар',
    addressLabel: 'Адрес', address: 'г. Самара, ул. Куйбышева, 100',
    hoursLabel: 'Часы работы',
    daysWeek: 'Пн – Чт, Вс', daysWend: 'Пт – Сб',
    mapLabel: 'Открыть на Яндекс.Картах',
    footerBookingRules: 'Правила бронирования',
    footerPrivacy: 'Политика конфиденциальности',
    footerCopy: '© 2025 The Cat\'s Pajamas Club · Самара',
  },
  en: {
    langBtn: 'RU',
    navAbout: 'Legend', navMenu: 'Drinks', navEvents: 'Bill',
    navGallery: 'Shelf', navTeam: 'Bartenders', navContacts: 'Find Us',
    navLoginTg: 'Log in with Telegram', navProfile: 'Profile',
    navAdmin: 'Admin Panel',
    heroEdition: 'The Bar Menu',
    heroCta: 'Reserve a Table',
    heroTagline: 'Where the Jazz Never Stops',
    heroSub: 'Samara · Cocktails · Live Music',
    heroNext: 'Open the Menu',

    aboutLabel: 'Chapter I · The Legend',
    aboutQuote: '"Where jazz plays even in the silence"',
    // Mirror of the RU legend. Deliberately no opening hours (they live in "Find Us"),
    // no item counts and no cocktail/infusion names — the menu changes constantly.
    aboutText: [
      'The Cat\'s Pajamas Club — Pizhama Kota to its regulars — is an intimate craft cocktail bar in the heart of Samara, on Kuybysheva Street. Guests have more than once called it the best bar in town, and we work to earn that every night. Inside: the mood of a 1980s New York bar — dark wood, brass and velvet, low light, live jazz and a panoramic window over the evening city.',
      'The name says it all: we deliberately left snobbery and pretense at the door. We build every cocktail like a short play — with its own character, an unexpected turn, and a taste worth remembering. And to get yours, you don\'t need to know the menu: just tell us what you like, and the bartender already knows what to do.',
      'The bartender is the hero of the evening. They\'ll ask about your habits and your mood and mix a drink made just for you, sometimes with a private name that\'s yours alone. Guests call it magic, or art; we simply hit the taste right. We take pride not in the length of the list, but in the craft behind the bar — every recipe is born right here, in front of you.',
      'Our house infusions are a point of pride: steeped slowly right behind the bar, and we welcome every guest with a taste from that collection. We take quality seriously — spirits on a par with the world\'s best bars and a thoughtful wine list, from rare finds to fine local wines. And the alcohol-free cocktails are made with the same care as the rest, so the evening lands even for those who are driving tonight.',
      'But people don\'t come here for the drinks alone. Pizhama Kota is where you walk in not to a bar, but as if visiting friends: a warm room, personal attention, and conversations that matter. The interior is full of details you\'ll want to study, and the water on your table never runs out all evening. Weeknights are quiet and intimate; weekends bring live music.',
      'This is a place for those who value taste and feel the difference between good and ordinary — for an unhurried evening with someone you love or people close in spirit. You come here to take your time: to sip slowly, talk about anything, and leave only when you\'ve truly had your fill — of the drinks and of the evening itself. Drop by, and just tell us what you like.',
    ],

    // NB: cocktail content itself is RU-only (owner's decision) — these are
    // just the surrounding UI labels for the EN toggle.
    menuLabel: 'Chapter II · The Drinks List', menuTitle: 'The Cocktail List',
    menuClassics: 'Classic', menuSignature: 'Signature',
    menuCta: 'Reserve a Table',
    menuLoading: 'Loading the menu…',
    menuEmpty: 'The menu is coming soon.',
    menuStoryLabel: 'About this section',
    menuPrintLink: 'Open the menu as a separate page',

    eventsLabel: 'Chapter III · Evening Bill', eventsTitle: 'The Jazz Program',
    eventsLoading: 'Loading events…',
    eventsEmpty: 'No upcoming events yet — check back soon.',

    galleryLabel: 'Chapter IV · Every Guest, Their Own Bottle', galleryTitle: 'Shelf of Memories',
    galleryIntro: 'Every guest review becomes a bottle on our shelf. Take a look — you might recognize someone\'s evening.',

    teamLabel: 'Chapter V · Behind the Bar', teamTitle: 'Masters Behind the Bar',
    teamSub: 'Each of our bartenders is a story lived through cocktails.',
    teamLoading: 'Loading the team…',
    teamEmpty: 'The team page is coming soon.',
    teamJoinText: 'Share your experience — we\'re looking for the best bartenders',
    teamJoinBtn: 'Apply Now',
    teamJoinAsk: 'Want to join a team of professionals?',
    teamJoinShare: 'Share your experience',
    teamJoinName: 'Your name',
    teamJoinPhone: 'Phone',
    teamJoinExp: 'A bit about your experience',
    teamJoinSend: 'Send',
    teamJoinSuccess: 'Thank you! We\'ll be in touch soon.',

    reviewsLoading: 'Arranging the bottles…',
    reviewsEmpty: 'The shelf is empty — be the first to leave a memory.',
    shelfCtaLoggedOut: 'Sign in to leave a review',
    shelfCtaLoggedIn: '📝 Leave a review',
    shelfModalTitle: 'Fill the shelf',
    shelfModalText: 'Reviews live in our Telegram discussion. Post a message there and it will appear here as a new bottle.',
    shelfModalBtn: 'Leave a memory',
    shelfModalClose: 'Close',
    shelfReadClose: 'Close',

    bookingLabel: 'The Final Page', bookingTitle: 'Claim Your Table',
    phoneLabel: 'Phone',

    // ─── Booking v2 (floor plan + request) ───
    bkDateLabel: 'Date', bkTimeLabel: 'Arriving at',
    bkToday: 'Today', bkTomorrow: 'Tomorrow',
    bkClosedToday: 'Requests for tonight are closed — pick another day',
    bkLoading: 'Loading the floor plan…',
    bkStatusVacant: 'Free', bkStatusReservedAt: 'Booked for', bkStatusOccupied: 'Taken',
    bkBarNote: 'The bar counter is walk-in only',
    bkLegendVacant: 'Free', bkLegendReserved: 'Booked', bkLegendOccupied: 'Taken',
    bkTableWord: 'Table', bkSofa: 'Sofa',
    bkZoneMain: 'Main hall', bkZoneWindow: 'By the window', bkZoneSofas: 'Sofas',
    bkSeatsLabel: 'seats',
    bkPanelHint: 'Pick a free table on the plan',
    bkPanelPhone: 'No Telegram? Book by phone:',
    bkReservedText: 'This table is already spoken for tonight — pick another one.',
    bkOccupiedText: 'This table is taken right now. Pick another — or come sit at the bar, it\'s walk-in only.',
    bkAuthText: 'The floor plan is open to everyone — booking requires a Telegram login.',
    bkAuthBtn: 'Log in with Telegram',
    bkFormName: 'Your name *', bkFormPhone: 'Phone',
    bkFormGuests: 'Guests', bkFormNote: 'Requests',
    bkFormNotePh: 'A birthday, a table near the stage…',
    bkFormSubmit: 'Send request', bkFormSubmitting: 'Sending…',
    bkConfirmNote: 'A bartender confirms every booking — you\'ll get a Telegram notification.',
    bkSuccessTitle: 'Request sent!',
    bkSuccessText: 'A bartender confirms every booking — it usually takes a few minutes. The notification will arrive in Telegram from @cats_pajama_bot.',
    bkSuccessWhere: 'Track the status in your profile or in the bot\'s "My bookings".',
    bkSuccessOk: 'Got it',
    bkDepositLabel: 'Deposit',
    bkDepositNote: 'Payable in "My bookings" once a bartender confirms. The deposit counts toward your bill.',
    bkSuccessDeposit: 'Once confirmed, pay the deposit in "My bookings" — it counts toward your bill.',
    bkTgFallbackText: 'Can\'t find the right table? Big party?',
    bkTgFallbackText2: 'Drop us a line on Telegram — we\'ll figure something out 🎷',
    bkTgFallbackBtn: 'Message us on Telegram',

    contactsLabel: 'Chapter VI · Find Us', contactsTitle: 'Find The Bar',
    addressLabel: 'Address', address: 'Samara, Kuybysheva St, 100',
    hoursLabel: 'Hours',
    daysWeek: 'Mon – Thu, Sun', daysWend: 'Fri – Sat',
    mapLabel: 'Open on Yandex Maps',
    footerBookingRules: 'Booking Rules',
    footerPrivacy: 'Privacy Policy',
    footerCopy: '© 2025 The Cat\'s Pajamas Club · Samara',
  },
};


